IMAGE_ROOT = "/mnt/ias-images"
INSTANCE_COUNT = 1
WORKERS_PER_INSTANCE = 1
GPU_ID = "cpu"

[Person_Thresd]
Head = 0.25
Top_Head = 0.1
Hat = 0.1
Headphones = 0.1
Shoulder = 0.1

[Face_Thresd]
face = 0.1

[Student_Thresd]
Using_phone = 0.3
Hand_raising = 0.75
Sleep = 0.15
standing = 0.2
Read_W = 0.4
