FROM nvidia/cuda:11.3.1-cudnn8-runtime-ubuntu20.04

LABEL authors="SeaCraft"

ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Asia/Shanghai

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt-get update && \
    apt-get install -y \
        python3.8 \
        python3.8-distutils \
        python3.8-dev \
        python3-pip \
        git \
        jq \
        curl \
        nginx \
        libgl1-mesa-glx \
        libglib2.0-0 \
        libsm6 \
        libxrender1 \
        libxext6 \
        libfontconfig1 \
        libice6 && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

RUN ln -sf /usr/bin/python3.8 /usr/bin/python3 && \
    ln -sf /usr/bin/python3.8 /usr/bin/python

RUN curl https://bootstrap.pypa.io/pip/3.8/get-pip.py | python3.8 && \
    ln -sf /usr/local/bin/pip3.8 /usr/bin/pip && \
    python -m pip install --upgrade pip

RUN pip install torch==1.12.1+cu113 torchvision==0.13.1+cu113 torchaudio==0.12.1 \
    --extra-index-url https://download.pytorch.org/whl/cu113 \
    -i https://mirrors.aliyun.com/pypi/simple/

WORKDIR /workspace

COPY ./tias ./tias
COPY ./tias/docker/nginx.conf /etc/nginx/nginx.conf

RUN pip install -i https://mirrors.aliyun.com/pypi/simple/ -r tias/requirements_cuda113.txt

ENV PYTHONUNBUFFERED=1 \
    CONFIG_PATH=/workspace/tias/config.toml

RUN chmod +x tias/start.sh

EXPOSE 8881
CMD ["/bin/bash", "-c", "tias/start.sh"]
